services:
  ndp-agent:
    build:
      context: .
      dockerfile: Dockerfile
      # Target the 'cpu' stage in your Dockerfile
      target: cpu
    # Tag this image as the CPU version
    image: lucyzeta/ndp-agent:cpu
    restart: always
    environment:
      - NDP_OWNER_ID=node-provider-lucy
      - NDP_NODE_NAME=BC01-Miner
    privileged: true
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      # These volumes are needed for BOTH CPU and GPU versions
      - ./agent-data:/app/
      - /mnt:/mnt:ro
      - /proc/mounts:/host/mounts:ro
    depends_on:
      - otel-collector

  translator:
    build: ./translator
    image: lucyzeta/translator:latest
    container_name: translator
    environment:
      - BACKEND_URL=http://211.176.180.172:8080/api/v1/nodes/telemetry
    ports:
      - "5001:5001"

  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    container_name: otel-collector
    command: ["--config=/etc/otelcol-contrib/config.yaml"]
    volumes:
      - ./otel-collector-config.yaml:/etc/otelcol-contrib/config.yaml
    ports:
      - "4317:4317"
    depends_on:
      - translator